export const commonAmenities = [
    "Free Wi-Fi",
    "Parking",
    "Swimming Pool",
    "Fitness Center",
    "Restaurant",
    "Bar/Lounge",
    "24-Hour Front Desk",
    "Room Service",
    "Air Conditioning",
    "Breakfast Included",
    "Spa",
    "Hot Tub/Jacuzzi",
    "Meeting/Banquet Facilities",
    "Laundry Service",
    "Pet-Friendly",
    "Airport Shuttle",
    "Concierge Service",
    "Non-Smoking Rooms",
    "Family Rooms",
    "Elevator",
  ];